env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
language: node_js
node_js:
  - 12
cache:
  yarn: true
install: yarn
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn lint
  - yarn test --coverage
after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
